# Generated by Django 5.2.3 on 2025-07-02 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('race', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('H', 'Hispanic'), ('A', 'Asian'), ('U', 'Unknown')], default='U', max_length=1)),
                ('case_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date_filed', models.DateField()),
                ('charges', models.TextField()),
                ('arrest_citation_date', models.DateField(blank=True, null=True)),
                ('parish', models.CharField(max_length=100)),
                ('alert_available', models.BooleanField(default=False)),
                ('scraped_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_filed'],
                'indexes': [models.Index(fields=['defendant_name'], name='scraper_cri_defenda_213135_idx'), models.Index(fields=['case_number'], name='scraper_cri_case_nu_e9691a_idx'), models.Index(fields=['parish'], name='scraper_cri_parish_800082_idx')],
            },
        ),
    ]
